### ISSUE TITLE
Error while launching server: Didn't include pry in jar build

### ISSUE THREAD

**Issue by UnknownSilicon** [RMHSProgrammingClub/Bot-Server#2]
![image](https://cloud.githubusercontent.com/assets/14339279/12187128/0796edce-b577-11e5-9a84-a4cedb722092.png)

**Comment by n9Mtq4** [comment]
It looks like Jake forgot to add a library when compiling it to a jar.

**Comment by n9Mtq4** [comment]
It appears as if this line in map.rb "require 'pry'" is the thing that is causing the problems. This was added in commit 57f96a7a457fc63cbf6e6677781c423f74c147e9. I recommend that you use a server released before this commit and nag Jake about fixing this issue.

**Comment by jakekinsella** [comment]
The fix will be included in the next release
