### ISSUE TITLE
Maths.rb is useless

### ISSUE THREAD

**Issue by UnknownSilicon** [RMHSProgrammingClub/Bot-Server#6]
Why...

**Comment by UnknownSilicon** [comment]
YES THIS WILL FIX

**Comment by UnknownSilicon** [comment]
I BLAME @TheLocust3

**Comment by n9Mtq4** [comment]
This is an older file that isn't used, so it should be deleted but it isn't worth the effort because unless there is a VERY VERY VERY big bug in the server don't expect to convince @TheLocust3 to compile a new one anytime soon.
